'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CartoonersFileViewerProgram.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:	Type:	Offset:	Related:	Size:	Comment:
        '''8086 executable code.	binary	0	0	156217	Compiled with the Microsoft C Compiler 5.10 (1988).
        '''PIT configuration procedure.	8086_code	64482	0	46	Configures the system timer to run faster and redirects interrupt 0x08.
        '''About Cartooners	text	208068	0	226	
        '''About dialog text alignment.	binary	208066	0	1	
        '''Actors dialog.	text	215400	0	36	
        '''Background screen buffer.	rectangles	207590	0	8	
        '''Blank... (act option)	text	203866	0	11	
        '''Buffer for speech balloon text in [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cartooners_Executable() As String
            Get
                Return ResourceManager.GetString("Cartooners_Executable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:	Address:
        '''INT 0x08 offset.	55F4
        '''INT 0x08 segment.	55F6
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Cartooners_Executable_Near_Addresses() As String
            Get
                Return ResourceManager.GetString("Cartooners_Executable_Near_Addresses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cartooners&apos; File Formats, by: Peter Swinkels ***2015***
        '''
        '''[General Program Information]
        '''Cartooners 1988/1989 - by: Electronic Arts &amp; IDTA
        '''
        '''Note:
        '''This document primarily applies to the program&apos;s MS-DOS version. The last section provides a brief summary of the file formats used by the Apple IIGS version.
        '''
        '''===================================================================================================
        '''
        '''[Animated Actors]
        '''
        '''[File Information]
        '''Endianess: little.
        '''Extension: *.act
        '''
        '''[File Layout]
        '''B [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cartooners_File_Formats() As String
            Get
                Return ResourceManager.GetString("Cartooners_File_Formats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cartooners File Viewer - Help
        '''
        '''[About Cartooners]
        '''Note: this is not meant to be a complete description of Cartooners. See the manual that comes with that program for more information.
        '''
        '''Cartooners is a basic animation software package originally developed for the Apple IIGS by ITDA and published by Electronic Arts in 1987 primarily aimed at children. It has also been ported to run under MS-DOS among others. With Cartooners the user can make a simple animated movie by placing static or animated actors ov [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cartooners_File_Viewer_Help() As String
            Get
                Return ResourceManager.GetString("Cartooners_File_Viewer_Help", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
